### PR TITLE
Enable Auth0

### PR DESCRIPTION
**Pull request by nickcannariato**
# Description

This replaces the old team's Auth0 credentials with our own credentials. 

**PR IS NOW READY FOR REVIEW AND HAS BEEN TESTED**

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Change status
- [x] Complete, tested, ready to review and merge
- [x] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?

This work was tested locally and worked, however, it should not be merged until @DaftBeowulf's forthcoming PR which alters our migrations and our database handlers to reflect the undocumented table schema of the original app and also the shift from MySQL to Postgres here: 
labs12-training-bot-2/labs12-training-bot-2-BE#3

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] There are no merge conflicts

### CODE REVIEW

**Comment by nickcannariato** [comment]
After testing this change with the code in labs12-training-bot-2/labs12-training-bot-2-BE#5 I have good news and bad news.

The good news is that it's "working" in that it's returning the proper credentials and also creating the new user as it should. 

The bad news is that for some unknown reason, it's making the POST call to `/api/auth` twice, and that second one is crashing the server before it has a chance to fully respond, which is preventing us from actually logging in. 

The reason the server is crashing is because of the `UNIQUE` contraint on the email column in the user's table, which we definitely do not want to change.

As for the double POST call to `/api/auth`, I confirmed with @lafriedel (who was on the original team that built the application) that this was happening in their application as well (though I'm unclear on why it wasn't crashing their application). So this appears to be a preexisting issue.

After looking through the code I'm not entirely sure what the cause is, though I _can_ confirm that it's happening because Redux is committing the `GET_USER_START` action twice.

If you time travel through the whole flow of actions in the Redux store, you'll see that it successfully logs in right before the `GET_USER_FAIL` action runs, which is also interesting and unexplained for me.

@ajb85 @TomHessburg @GannonDetroit @DaftBeowulf This is one I'm gonna need help diagnosing. The good news is that once this is done the application is fully deployed and working outside of Stripe, which I think @GannonDetroit has working and ready to submit.

**Comment by nickcannariato** [comment]
Ah, fun new fact, this issue only occurs on user _signup_. If you then go back to the home page and attempt to log in again it works as expected.

**Comment by nickcannariato** [comment]
I have a theory, I think this might be because the axios call to create the user is inside the GET_USER_START action, which is being triggered by the `getUser()` call inside of the `componentDidMount()` method in the Dashboard component. 

This results in a flow that looks like this:

1. Component mounts => getUser() runs => Triggers GET_USER_START action => updates Dashboard State to Loading
2. State is now updated => component mounts => getUser() runs => Previous action hadn't completed yet so no user => attempt to create user again
3. First GET_USER_START action completes successfully, returns the new user, starts other actions
4. Second GET_USER_START action fails, resets loading state, component hangs.

When you log in as an existing user, you can see the GET_USER_START and GET_USER_SUCCESS actions happen twice as well, so I _think_ I'm on the right track here. Just not sure how to fix it yet.

**Comment by nickcannariato** [comment]
Did some debugging with @DaftBeowulf and we confirmed my above theory ☝️ 

The issue is that GET_USER_START is changing the state of the DashboardView component, which is causing it to re-render before the first GET_USER_START action can complete. 

He's going to play around with that while I relocate to grab some coffee. ☕️

**Comment by DaftBeowulf** [comment]
Issue verified-- @nickcannariato and I spent some time this morning playing around with changing the default store state's isLoading prop, commenting out the GET_USER_START case in both action and reducers so it only returns default state, issue still persists. Multiple componentDidMounts firing with 1 ms or less time apart (tracked via Date.now() logs and Redux tools), not enough time passing between CDM triggers for the second call to be cancelled out. In production, there is a little more lag time when authenticating which is why the issue is only visible in development.

**Comment by nickcannariato** [comment]
To add to the above comment ☝️ 

I just deleted my account on TrainingBot 1 and watched the Redux store / the console return the same errors we're seeing. However, the error is returned _first_ and the success is returned _second_, which makes all the difference in the world (and is likely do to infra lag).

I'm going to test this in production and see if we see the same error.

**Pull request merged**
